# Generated by Django 2.1.5 on 2019-01-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBoardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_file', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('extra_environment', models.TextField(blank=True, default='', max_length=1024, null=True)),
                ('command', models.CharField(default='', max_length=256)),
                ('working_dir', models.CharField(default='', max_length=256)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('kind_of_task', models.CharField(blank=True, choices=[('XL', 'XILINX'), ('FP', 'FPGA'), ('FT', 'FPGA Time Sensitive')], default='XL', max_length=2)),
                ('state', models.CharField(blank=True, choices=[('PR', 'Processing'), ('IQ', 'In Queue'), ('FN', 'Finished')], default='IQ', max_length=2)),
                ('pid', models.IntegerField(blank=True, default=0, null=True)),
                ('started', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(max_length=10240)),
            ],
        ),
        migrations.AddField(
            model_name='scheduleboarditem',
            name='log',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.SchedulerLog'),
        ),
    ]
