# Generated by Django 2.1.5 on 2019-01-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_file', models.CharField(default='', max_length=256)),
                ('extra_environment', models.TextField(default='', max_length=1024)),
                ('command', models.CharField(default='', max_length=256)),
                ('working_dir', models.CharField(default='', max_length=256)),
                ('state', models.CharField(choices=[('PR', 'Freshman'), ('IQ', 'Sophomore'), ('FN', 'Junior')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(max_length=10240)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='scheduleboard',
            name='log',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scheduler.SchedulerLog'),
        ),
    ]
