# Generated by Django 2.1.7 on 2019-02-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleboarditem',
            name='timeslot_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='scheduleboarditem',
            name='state',
            field=models.CharField(blank=True, choices=[('PR', 'Processing'), ('IQ', 'In Queue'), ('FN', 'Finished'), ('KL', 'Killed')], default='IQ', max_length=2),
        ),
    ]
