# Generated by Django 2.1.5 on 2019-01-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20190120_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleboard',
            name='environment_file',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleboard',
            name='extra_environment',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleboard',
            name='log',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.SchedulerLog'),
        ),
        migrations.AlterField(
            model_name='scheduleboard',
            name='state',
            field=models.CharField(blank=True, choices=[('PR', 'Processing'), ('IQ', 'In Queue'), ('FN', 'Finished')], default='IQ', max_length=2),
        ),
    ]
