# Generated by Django 2.1.5 on 2019-01-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20190120_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleBoard',
            new_name='ScheduleBoardItem',
        ),
    ]
