# Generated by Django 2.1.5 on 2019-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20190120_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleboarditem',
            name='finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scheduleboarditem',
            name='started',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
