# Generated by Django 2.1.5 on 2019-01-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20190120_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleboarditem',
            name='kind_of_task',
            field=models.CharField(blank=True, choices=[('XL', 'XILINX'), ('FP', 'FPGA'), ('FT', 'FPGA Time Sensitive')], default='XL', max_length=2),
        ),
        migrations.AlterField(
            model_name='scheduleboarditem',
            name='log',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.SchedulerLog'),
        ),
    ]
